// ITCS355 Lab 3 — load test.
//
//   TOKEN=$(make loadtest-token) k6 run -e TARGET=https://<endpoint>/predict \
//     -e VUS=10 -e TOKEN=$TOKEN loadtest/k6.js
//
// Run at THREE concurrency levels (1, 10, 50) and record p50, p95, p99, throughput,
// and error rate for each. Commit the results in reports/lab3-load.md.
//
// An uncommitted load test is not evidence.
//
// Stated target (reports/lab3-load.md, committed before any of these numbers existed):
//   p95 <= 200ms @ concurrency 10, error rate < 1%
//
// Two scenarios per run: `warmup` (excluded from every metric below — it never calls
// latency.add()/failures.add() at all) runs first, then `measure` is what the
// thresholds and the exported summary are actually built from.

import http from 'k6/http';
import { check } from 'k6';
import { Trend, Rate } from 'k6/metrics';
import { SharedArray } from 'k6/data';

const holdoutRows = new SharedArray('holdout', function () {
  // Real held-out test rows, never training rows, never one row repeated — generated by
  // `python scripts/export_holdout_rows.py` (make loadtest-rows / make loadtest runs it
  // for you).
  return JSON.parse(open('./holdout_rows.json'));
});

const latency = new Trend('predict_latency_ms');
const failures = new Rate('predict_failures');

const VUS = Number(__ENV.VUS || 10);
const WARMUP_SECONDS = Number(__ENV.WARMUP_SECONDS || 10);
const DURATION_SECONDS = Number(__ENV.DURATION_SECONDS || 60);
const TARGET = __ENV.TARGET;
const TOKEN = __ENV.TOKEN;

if (!TARGET) throw new Error('set -e TARGET=https://<endpoint>/predict');
if (!TOKEN) throw new Error('set -e TOKEN=<identity token> — see make loadtest-token');

export const options = {
  // k6's default trend stats are avg/min/med/max/p(90)/p(95) — p(99) is NOT included
  // unless listed here, and 'med' is p50 by definition (no separate 'p(50)' key exists).
  summaryTrendStats: ['avg', 'min', 'med', 'p(90)', 'p(95)', 'p(99)', 'max'],
  scenarios: {
    warmup: {
      executor: 'constant-vus',
      vus: VUS,
      duration: `${WARMUP_SECONDS}s`,
      exec: 'warmupIteration',
      startTime: '0s',
    },
    measure: {
      executor: 'constant-vus',
      vus: VUS,
      duration: `${DURATION_SECONDS}s`,
      exec: 'measureIteration',
      startTime: `${WARMUP_SECONDS}s`,
    },
  },
  thresholds: {
    // The target stated in reports/lab3-load.md BEFORE any number below existed.
    predict_latency_ms: ['p(95)<200'],
    predict_failures: ['rate<0.01'],
  },
};

function randomPayload() {
  return holdoutRows[Math.floor(Math.random() * holdoutRows.length)];
}

function doRequest() {
  return http.post(TARGET, JSON.stringify(randomPayload()), {
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${TOKEN}`,
    },
  });
}

export function warmupIteration() {
  doRequest(); // deliberately not recorded into predict_latency_ms/predict_failures
}

export function measureIteration() {
  const res = doRequest();
  latency.add(res.timings.duration);
  failures.add(res.status !== 200);
  check(res, {
    'status is 200': (r) => r.status === 200,
    'probability present': (r) => r.status === 200 && r.json('probability') !== undefined,
    'version reported': (r) => r.headers['X-Model-Version'] !== undefined,
  });
}

export function handleSummary(data) {
  const m = data.metrics;
  const pct = (name, p) => (m[name] && m[name].values[p] !== undefined ? m[name].values[p].toFixed(2) : 'n/a');
  // predict_failures.add() runs once per measure-phase iteration (never in warmup), so
  // passes+fails is exactly the measure-phase request count — http_reqs would also
  // count warmup traffic and isn't scenario-scoped here.
  const measureCount = m.predict_failures ? m.predict_failures.values.passes + m.predict_failures.values.fails : 'n/a';
  const outPath = `reports/raw/lab3-load-vus${VUS}.json`;
  const lines = [
    `=== VUS=${VUS} (warmup=${WARMUP_SECONDS}s, measure=${DURATION_SECONDS}s) ===`,
    `requests (measure phase): ${measureCount}`,
    `predict_latency_ms  p50=${pct('predict_latency_ms', 'med')}  ` +
      `p95=${pct('predict_latency_ms', 'p(95)')}  p99=${pct('predict_latency_ms', 'p(99)')}`,
    `predict_failures rate=${m.predict_failures ? m.predict_failures.values.rate : 'n/a'}`,
    `wrote ${outPath}`,
  ];
  return {
    [outPath]: JSON.stringify(data, null, 2),
    stdout: lines.join('\n') + '\n',
  };
}
